on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
env:
  IMAGE_NAME: lnbits


jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' 
    steps:
        - uses: actions/checkout@v2
        - name: Executing remote  command
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.SSH_HOST}} 
            key: ${{secrets.SSH_KEY}} 
            username: ${{ secrets.SSH_USERNAME }} 
            script: |
              git clone https://github.com/lnbits/lnbits.git
              cd lnbits/
              apt install python3-venv
              python3 -m venv venv
              ./venv/bin/pip install -r requirements.txt
              cp .env.example .env
              mkdir data
              ./venv/bin/quart assets
              ./venv/bin/quart migrate
              ./venv/bin/hypercorn -k trio --bind 0.0.0.0:5000 'lnbits.app:create_app()'

              
